### ISSUE TITLE
The uuid becomes invalid after the reconnection

### ISSUE THREAD

**Issue by cmmmm660** [Velorexe/Unity-Android-Bluetooth-Low-Energy#14] opened 2022-11-21 09:14 UTC
Hello @Velorexe 
I used an Android device to connect to the ble Bluetooth module.  Once the module is connected, I subscribe to the module's UUID for sending and receiving data.  Then disconnect the module and connect the module to subscribe to the module's UUID.  The next problem is that the UUID that receives the data is subscribed, but cannot receive the data sent by the module, and the same is true for the send

**Comment by Velorexe** [comment] 2022-11-22 08:08
Hi,

I'm not sure if I'm following you here. You
- successfully connected to the BLE module
- subscribed to a characteristic
- disconnected
- reconnected to the BLE module
- subscribed to a characteristic

When reconnected a second time to the same characteristic, you don't receive nor can send any data?

**Comment by cmmmm660** [comment] 2022-11-22 08:18
Hi,
Yes! Before that, I still have a question. Why can’t I scan the scanned device name and address again?

**Comment by cmmmm660** [comment] 2022-11-22 08:33
The detailed process of reconnection is as follows
• 1. It is normal to connect the Bluetooth module at the beginning, and then subscribe to the UUID.
• 2. Next, I will unplug the module, which means the bluetooth signal will be disconnected. At this time, the OnDisconnected method will be triggered.

![image](https://user-images.githubusercontent.com/71002391/203264472-9391be82-916d-41ec-9c54-7dd92f5baf95.png)

![image](https://user-images.githubusercontent.com/71002391/203264567-b69ffb9b-97dc-4483-9670-5c074a6a70d4.png)

**Comment by Velorexe** [comment] 2022-11-22 10:04
Then I believe it's something in the Java library, when `subscribeFromGattCharacteristic` is called the flags of the characteristic are set to enable notifications, so it might be that  `unsubscribeFromGattCharacteristic` sets some flags on the characteristic or descriptor that prevents the device from sending new information.

I'll have a look at it.

As per your other question: I don't clear the list of already discovered devices from the Java library, but didn't add a method to retrieve the already discovered devices. I'll probably make a boolean on the scan command to clear the already discovered devices when scanning.

**Comment by cmmmm660** [comment] 2022-11-23 01:03
> 
expect,
thank you very much！！

**Comment by cmmmm660** [comment] 2022-11-23 08:23
hi,
I found that the jsonMessage disconnection or reconnection of the OnBleMessage method in the BleAdapter class will print out this information. Maybe you have judged this wrong in java. I hope it works for you. The bluetooth projects you create are very important to me. Hope to solve Thank you!

![image](https://user-images.githubusercontent.com/71002391/203500102-47b4e33d-b063-443a-9054-c95df9ab14ce.png)

**Comment by Velorexe** [comment] 2022-11-26 12:57
I'm glad to hear that my BLE project is useful to you!
I'll take a look at the issue asap. Hope to get back to you soon.

**Comment by Velorexe** [comment] 2022-11-27 13:03
Hi @cmmmm660 

I've created a branch with a fix that worked when I reproduced your issue locally.
It seems to have been an issue with the order in which I disconnect the GATT server from the Java library. The `disconnect()` was called before the `close()`, so the server never really closed it's communication with the client (my BLE plugin).

Now it properly disconnects from the GATT server. I hope this will solve your problem.
The branch is called [`fix/subscribe-reconnect`](https://github.com/Velorexe/Unity-Android-Bluetooth-Low-Energy/tree/fix/subscribe-reconnect)

**Comment by cmmmm660** [comment] 2022-11-28 02:49
Hi @Velorexe 
Thank you very much for your timely feedback and fixing the problems I encountered!
I use the latest branch, unfortunately there is still a problem with reconnecting, the error message is the same as before, but I also found that disconnecting the module after reconnecting does not seem to print the disconnection message, hope it is useful to you.

![image](https://user-images.githubusercontent.com/71002391/204180857-0fae0a6f-0768-40cc-bbe0-f472bd0c7b4a.png)
![image](https://user-images.githubusercontent.com/71002391/204180992-10762bed-aa21-429a-ab3b-d118a89f0541.png)

**Comment by Velorexe** [comment] 2022-11-29 08:20
Hi @cmmmm660 

Turns out, I added the changes to the branch with cherry picking, which only filters on lines and didn't track that I changed the Android library itself. I've added it and pushed it to the previously mentioned `fix/subscribe-reconnect` branch. Hope it works for you now!

**Comment by cmmmm660** [comment] 2022-11-30 03:30
Holle @Velorexe 
I used the fix/subscribe-reconnect branch and it reconnects now works fine, my problem was fixed, it was a big help, thank you so much for fixing it in time, it's too much for me Important, thank you very much! ! !

**Comment by Velorexe** [comment] 2022-11-30 07:01
No problem! Glad it fixed your problem and thanks for using my library.

**Closed** 2022-11-30 07:02 UTC
